
version: "3.8"
services:

    # PHP service
    app:
      build: 
        context: .
        dockerfile: Dockerfile
      container_name: app
      extra_hosts:
        - "host.docker.internal:host-gateway"
      working_dir: /var/www/
      volumes:
        - ./public:/var/www
      networks:
        - hive-network

    # MySQL database service
    db:
      build:
        context: .
        dockerfile: MYSQLDockerfile
      container_name: mysql
      extra_hosts:
        - "host.docker.internal:host-gateway"
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
      volumes:
        - ./public:/var/www
        - mysql-data:/var/lib/mysql:delegated
      env_file:
        - ./.env
      networks:
        - hive-network

    # Nginx service
    nginx:
      build:
        context: .
        dockerfile: NGINXDockerfile
      container_name: nginx
      ports:
        - 80:80
      volumes:
        - ./public:/var/www
        - ./nginx/conf.d/:/etc/nginx/conf.d/
      networks:
        - hive-network

networks:
    hive-network:
        driver: bridge
volumes:
  mysql-data:
