version: "3.3"
services:

    # MySQL database service
    db:
        build: ./.mysql
        container_name: mysql-db
        working_dir: /var/www
        ports:
            - "3306:3306"
        volumes:
            - ./.mysql/scripts/:/var/www
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_HOST: ${DB_HOST}
        env_file:
            - ./.env
        networks:
            - php-app-network

    # PHP service
    app:
        build: ./.php
        container_name: php-app
        working_dir: /var/www/
        volumes:
            - ../:/var/www
        networks:
            - php-app-network

    # Nginx service
    nginx:
        image: nginx:alpine
        container_name: php-nginx
        working_dir: /var/www/
        ports:
            - 8000:80
        volumes:
            - ../:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - php-app-network

networks:
    php-app-network:
        driver: bridge
